import {
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  ArrowLeft,
  Bold,
  Briefcase,
  Building2,
  Calendar,
  CalendarClock,
  Check,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleDot,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Code,
  Coffee,
  Database,
  FileText,
  Flag,
  GraduationCap,
  Handshake,
  Hash,
  History,
  Home,
  Image,
  Info,
  Italic,
  Languages,
  LayoutDashboard,
  LayoutGrid,
  List,
  ListFilter,
  ListTree,
  Loader2,
  type LucideIcon,
  MapPin,
  MessageSquare,
  Mic,
  Minus,
  MoreHorizontal,
  MousePointerClick,
  Paperclip,
  Pencil,
  PenTool,
  Phone,
  Plus,
  Presentation,
  Search,
  Settings,
  Settings2,
  ShieldCheck,
  SlidersHorizontal,
  Star,
  TicketPlus,
  Timer,
  Trash2,
  Type,
  Underline,
  UserRound,
  Users,
  Video,
  Wifi,
  WifiOff,
  X,
} from "lucide-react";

/** Stable icon names persisted on entities, decoupled from the underlying icon library. */
export enum TomatoIconKey {
  AlignCenter = "align-center",
  AlignJustify = "align-justify",
  AlignLeft = "align-left",
  AlignRight = "align-right",
  ArrowLeft = "arrow-left",
  Bold = "bold",
  Briefcase = "briefcase",
  Building = "building",
  Calendar = "calendar",
  CalendarClock = "calendar-clock",
  Check = "check",
  CheckSquare = "check-square",
  ChevronDown = "chevron-down",
  ChevronLeft = "chevron-left",
  ChevronRight = "chevron-right",
  ChevronUp = "chevron-up",
  CircleDot = "circle-dot",
  ClipboardCheck = "clipboard-check",
  ClipboardList = "clipboard-list",
  Clock = "clock",
  Close = "close",
  Code = "code",
  Coffee = "coffee",
  Database = "database",
  Document = "document",
  Flag = "flag",
  GraduationCap = "graduation-cap",
  Handshake = "handshake",
  Hash = "hash",
  History = "history",
  Home = "home",
  Image = "image",
  Info = "info",
  Italic = "italic",
  Languages = "languages",
  LayoutDashboard = "layout-dashboard",
  LayoutGrid = "layout-grid",
  List = "list",
  ListFilter = "list-filter",
  ListTree = "list-tree",
  Loader = "loader",
  MapPin = "map-pin",
  Message = "message",
  Mic = "mic",
  Minus = "minus",
  MoreHorizontal = "more-horizontal",
  MousePointerClick = "mouse-pointer-click",
  Paperclip = "paperclip",
  Pencil = "pencil",
  PenTool = "pen-tool",
  Phone = "phone",
  Plus = "plus",
  Presentation = "presentation",
  Search = "search",
  Settings = "settings",
  Settings2 = "settings-2",
  ShieldCheck = "shield-check",
  SlidersHorizontal = "sliders-horizontal",
  Star = "star",
  TicketPlus = "ticket-plus",
  Timer = "timer",
  Trash = "trash",
  Type = "type",
  Underline = "underline",
  UserRound = "user-round",
  Users = "users",
  Video = "video",
  Wifi = "wifi",
  WifiOff = "wifi-off",
}

/** Every icon the system supports, keyed by the stable name persisted on entities. */
export const TOMATO_ICON_MAP = {
  [TomatoIconKey.AlignCenter]: AlignCenter,
  [TomatoIconKey.AlignJustify]: AlignJustify,
  [TomatoIconKey.AlignLeft]: AlignLeft,
  [TomatoIconKey.AlignRight]: AlignRight,
  [TomatoIconKey.ArrowLeft]: ArrowLeft,
  [TomatoIconKey.Bold]: Bold,
  [TomatoIconKey.Briefcase]: Briefcase,
  [TomatoIconKey.Building]: Building2,
  [TomatoIconKey.Calendar]: Calendar,
  [TomatoIconKey.CalendarClock]: CalendarClock,
  [TomatoIconKey.Check]: Check,
  [TomatoIconKey.CheckSquare]: CheckSquare,
  [TomatoIconKey.ChevronDown]: ChevronDown,
  [TomatoIconKey.ChevronLeft]: ChevronLeft,
  [TomatoIconKey.ChevronRight]: ChevronRight,
  [TomatoIconKey.ChevronUp]: ChevronUp,
  [TomatoIconKey.CircleDot]: CircleDot,
  [TomatoIconKey.ClipboardCheck]: ClipboardCheck,
  [TomatoIconKey.ClipboardList]: ClipboardList,
  [TomatoIconKey.Clock]: Clock,
  [TomatoIconKey.Close]: X,
  [TomatoIconKey.Code]: Code,
  [TomatoIconKey.Coffee]: Coffee,
  [TomatoIconKey.Database]: Database,
  [TomatoIconKey.Document]: FileText,
  [TomatoIconKey.Flag]: Flag,
  [TomatoIconKey.GraduationCap]: GraduationCap,
  [TomatoIconKey.Handshake]: Handshake,
  [TomatoIconKey.Hash]: Hash,
  [TomatoIconKey.History]: History,
  [TomatoIconKey.Home]: Home,
  [TomatoIconKey.Image]: Image,
  [TomatoIconKey.Info]: Info,
  [TomatoIconKey.Italic]: Italic,
  [TomatoIconKey.Languages]: Languages,
  [TomatoIconKey.LayoutDashboard]: LayoutDashboard,
  [TomatoIconKey.LayoutGrid]: LayoutGrid,
  [TomatoIconKey.List]: List,
  [TomatoIconKey.ListFilter]: ListFilter,
  [TomatoIconKey.ListTree]: ListTree,
  [TomatoIconKey.Loader]: Loader2,
  [TomatoIconKey.MapPin]: MapPin,
  [TomatoIconKey.Message]: MessageSquare,
  [TomatoIconKey.Mic]: Mic,
  [TomatoIconKey.Minus]: Minus,
  [TomatoIconKey.MoreHorizontal]: MoreHorizontal,
  [TomatoIconKey.MousePointerClick]: MousePointerClick,
  [TomatoIconKey.Paperclip]: Paperclip,
  [TomatoIconKey.Pencil]: Pencil,
  [TomatoIconKey.PenTool]: PenTool,
  [TomatoIconKey.Phone]: Phone,
  [TomatoIconKey.Plus]: Plus,
  [TomatoIconKey.Presentation]: Presentation,
  [TomatoIconKey.Search]: Search,
  [TomatoIconKey.Settings]: Settings,
  [TomatoIconKey.Settings2]: Settings2,
  [TomatoIconKey.ShieldCheck]: ShieldCheck,
  [TomatoIconKey.SlidersHorizontal]: SlidersHorizontal,
  [TomatoIconKey.Star]: Star,
  [TomatoIconKey.TicketPlus]: TicketPlus,
  [TomatoIconKey.Timer]: Timer,
  [TomatoIconKey.Trash]: Trash2,
  [TomatoIconKey.Type]: Type,
  [TomatoIconKey.Underline]: Underline,
  [TomatoIconKey.UserRound]: UserRound,
  [TomatoIconKey.Users]: Users,
  [TomatoIconKey.Video]: Video,
  [TomatoIconKey.Wifi]: Wifi,
  [TomatoIconKey.WifiOff]: WifiOff,
} satisfies Record<TomatoIconKey, LucideIcon>;

export const DEFAULT_TOMATO_ICON_KEY: TomatoIconKey = TomatoIconKey.Clock;
