version: "3.9"

services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: tomato_form
      POSTGRES_USER: tomato
      POSTGRES_PASSWORD: tomato

  yjs-server:
    build:
      context: ./yjs-server
    restart: unless-stopped
    ports:
      - "3028:3028"
    environment:
      HOST: "0.0.0.0"
      PORT: "3028"
      BACKEND_URL: http://server:3022
    depends_on:
      - server
  mail:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

  server:
    build:
      context: ./server
    restart: unless-stopped
    ports:
      - "3022:3022"
    environment:
      NODE_ENV: production
      PORT: "3022"
      DATABASE_URL: postgresql://tomato:tomato@postgres:5432/tomato_form
      CORS_ORIGIN: http://localhost:3021
    depends_on:
      - postgres

volumes:
  postgres_data:
