import {
  ApiCallMethod,
  ApiCallResponseType,
  ApiCallValueSource,
  type ApiCallConfig,
  type ApiCallKeyValue,
} from "@/types/api-call";
import {
  ButtonActionType,
  RecipientType,
  type ButtonAction,
} from "@/types/button-action";
import type { OptionItem, Widget, WidgetProperties } from "@/types/template";
import { generateKeyBetween } from "fractional-indexing";
import type {
  SerializedEditorState,
  SerializedLexicalNode,
  SerializedParagraphNode,
  SerializedTextNode,
} from "lexical";
import type { CSSProperties } from "react";
import { v4 } from "uuid";
import { z } from "zod";

const styleInput = z
  .record(z.string(), z.union([z.string(), z.number()]))
  .describe(
    'CSS properties in camelCase, e.g. { "color": "#ffffff", "background": "#3b82f6" }.',
  );

const buttonActionInput = z.discriminatedUnion("type", [
  z.object({
    type: z.literal(ButtonActionType.LINK),
    url: z.string().describe("Address to open."),
  }),
  z.object({
    type: z.literal(ButtonActionType.MAIL),
    recipients: z.array(
      z.object({
        type: z
          .nativeEnum(RecipientType)
          .describe("`mail` for an email address, `user` for a user uuid."),
        value: z.string(),
      }),
    ),
    subject: z.string(),
    body: z.string(),
  }),
]);

const apiCallKeyValueInput = z.object({
  key: z.string(),
  source: z
    .nativeEnum(ApiCallValueSource)
    .describe("`static` sends `value`, `widget` sends the value of `widgetId`."),
  value: z.string().optional(),
  widgetId: z.string().optional(),
});

const apiCallInput = z.object({
  hostId: z.string().optional(),
  method: z.nativeEnum(ApiCallMethod),
  url: z
    .string()
    .describe("May embed {{widget.label}} tokens, replaced by that widget's value."),
  params: z.array(apiCallKeyValueInput).optional(),
  headers: z.array(apiCallKeyValueInput).optional(),
  payload: z.string().optional(),
  response: z.object({
    type: z.nativeEnum(ApiCallResponseType),
    show: z.boolean().optional().describe("Display the response after it loads."),
    imageWidgetId: z
      .string()
      .optional()
      .describe("`image` responses only - widget to fill with the image."),
    jsonMappings: z
      .array(
        z.object({
          key: z.string().describe("Dot-path into the JSON response body."),
          widgetId: z.string().optional().describe("Widget to fill with that value."),
        }),
      )
      .optional()
      .describe("`json` responses only."),
  }),
});

/**
 * Every `WidgetProperties` key, in the shape a model can produce reliably:
 * ids, keys and indexes are generated by `toWidgetProperties`, rich text is
 * plain text. Shared by `addWidget` and `setWidgetProperties`.
 */
export const widgetPropertiesInput = z.object({
  label: z.string().optional(),
  placeholder: z.string().optional(),
  required: z.boolean().optional(),
  options: z
    .array(z.string())
    .optional()
    .describe(
      "Choices of select / checkbox / radio widgets, in order. Replaces the whole list.",
    ),
  content: z
    .string()
    .optional()
    .describe("Text of a label widget. A new line starts a new paragraph."),
  url: z.string().optional().describe("Legacy button link - prefer `actions`."),
  actions: z
    .array(buttonActionInput)
    .optional()
    .describe("Button widgets: actions run in order on click. Replaces the list."),
  apiCall: apiCallInput.optional().describe("api-call widgets: request configuration."),
  compact: z.boolean().optional().describe("Break widgets: render with less height."),
  textStyle: styleInput.optional(),
  containerStyle: styleInput.optional(),
});

export type WidgetPropertiesInput = z.infer<typeof widgetPropertiesInput>;

function sortByIndex(options: OptionItem[]): OptionItem[] {
  return [...options].sort((a, b) => (a.index < b.index ? -1 : 1));
}

/** Keeps the key of an option whose text is unchanged so existing answers still point at it. */
function toOptions(values: string[], existing: OptionItem[] = []): OptionItem[] {
  const keysByValue = new Map(existing.map((option) => [option.value, option.key]));
  let lastIndex: string | null = null;
  return values.map((value) => {
    const index = generateKeyBetween(lastIndex, null);
    lastIndex = index;
    return { key: keysByValue.get(value) ?? v4(), value, index };
  });
}

export function toEditorState(text: string): SerializedEditorState {
  const paragraphs = text.split("\n").map((line): SerializedParagraphNode => {
    const run: SerializedTextNode = {
      type: "text",
      version: 1,
      text: line,
      detail: 0,
      format: 0,
      mode: "normal",
      style: "",
    };
    return {
      type: "paragraph",
      version: 1,
      direction: "ltr",
      format: "",
      indent: 0,
      textFormat: 0,
      textStyle: "",
      children: line ? [run] : [],
    };
  });
  return {
    root: {
      type: "root",
      version: 1,
      direction: "ltr",
      format: "",
      indent: 0,
      children: paragraphs,
    },
  };
}

function nodeText(node: SerializedLexicalNode): string {
  if ("text" in node && typeof node.text === "string") return node.text;
  if (!("children" in node) || !Array.isArray(node.children)) return "";
  return node.children.map(nodeText).join("");
}

export function editorStateToText(state: SerializedEditorState): string {
  return state.root.children.map(nodeText).join("\n");
}

function toKeyValues(rows: z.infer<typeof apiCallKeyValueInput>[] = []): ApiCallKeyValue[] {
  return rows.map((row) => ({ id: v4(), ...row }));
}

function toApiCall(input: z.infer<typeof apiCallInput>): ApiCallConfig {
  return {
    ...input,
    params: toKeyValues(input.params),
    headers: toKeyValues(input.headers),
    response: {
      ...input.response,
      jsonMappings: input.response.jsonMappings?.map((mapping) => ({
        id: v4(),
        ...mapping,
      })),
    },
  };
}

/**
 * Widget ids in `input.apiCall` that are not in `widgets`. The model can
 * invent ids, so callers reject the call instead of saving dangling refs.
 */
export function findUnknownWidgetIds(
  input: WidgetPropertiesInput,
  widgets: Record<string, Widget>,
): string[] {
  const { apiCall } = input;
  if (!apiCall) return [];

  const referenced = [
    ...(apiCall.params ?? []).map((row) => row.widgetId),
    ...(apiCall.headers ?? []).map((row) => row.widgetId),
    apiCall.response.imageWidgetId,
    ...(apiCall.response.jsonMappings ?? []).map((mapping) => mapping.widgetId),
  ];
  return referenced.filter(
    (id): id is string => id !== undefined && !widgets[id],
  );
}

/**
 * Turns the model's input into stored properties. Only the keys the model
 * sent are returned, so the result can be spread over defaults or an
 * existing widget. `existing` is used to keep option keys stable.
 */
export function toWidgetProperties(
  input: WidgetPropertiesInput,
  existing?: Widget,
): Partial<WidgetProperties> {
  const { options, content, actions, apiCall, textStyle, containerStyle, ...scalars } =
    input;

  const properties: Partial<WidgetProperties> = { ...scalars };
  if (options) properties.options = toOptions(options, existing?.options);
  if (content !== undefined) properties.content = toEditorState(content);
  if (actions) properties.actions = actions satisfies ButtonAction[];
  if (apiCall) properties.apiCall = toApiCall(apiCall);
  if (textStyle) properties.textStyle = textStyle as CSSProperties;
  if (containerStyle) properties.containerStyle = containerStyle as CSSProperties;
  return properties;
}

/** What the copilot sees of a widget - the same vocabulary it writes with. */
export function describeWidget(widget: Widget) {
  return {
    id: widget.id,
    type: widget.type,
    label: widget.label,
    placeholder: widget.placeholder,
    required: widget.required,
    options: widget.options && sortByIndex(widget.options).map((option) => option.value),
    content: widget.content && editorStateToText(widget.content),
    url: widget.url,
    actions: widget.actions,
    apiCall: widget.apiCall,
    compact: widget.compact,
    textStyle: widget.textStyle,
    containerStyle: widget.containerStyle,
  };
}
